### ISSUE TITLE
Fix non-placeholder containing target values not checking exact match

### ISSUE THREAD

**Issue by cjustinn** [cjustinn/SpecialisedWorkforce2#47]
When a target includes a placeholder ('{*}', '{level}', etc.) they should be matched to any result which CONTAINS the target string. If the target value is a pure value with no placeholders, it should check for exact matches.

Ex: the following attribute matches not only STONE, but also matches END_STONE, which should not be covered since there are no placeholders in the 'STONE' value.

```
overworldblockbreaker:
  targets:
  - STONE
  - ANDESITE
  - DIORITE
  - GRANITE
  - DEEPSLATE
  - DRIPSTONE
  - SANDSTONE
  - TUFF
  - CALCITE
  chance: '{level} * 0.014'
  amount: '{level} * 0.06'
  levelThreshold: 0
  type: BONUS_BLOCK_DROPS
```
